# Generated by Django 5.0.2 on 2024-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=4, max_digits=13, max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('img', models.CharField(max_length=2083)),
            ],
        ),
    ]
